[metadata]
name = "git-log"
description = "Browse commit history."
requirements = ["git"]

[source]
command = "git log --graph --pretty=format:'%C(yellow)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --color=always"
output = "{strip_ansi|split: :1}"
ansi = true
no_sort = true
frecency = false

[preview]
command = "git show --patch --stat --pretty=fuller --color=always '{strip_ansi|split: :1}' | head -1000"

[keybindings]
enter = "actions:show"

[actions.show]
description = "Show commit details"
command = "git show --stat --patch --color=always '{strip_ansi|split: :1}' | ${PAGER:-less -R}"
mode = "execute"
