"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"
truncation_length = 3

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 500

[git_status]
disabled = true