# ==========================================================
# TMUX MODULES
# Status Bar Modules
# ==========================================================

# ----------------------------------------------------------
# Left
# ----------------------------------------------------------

set -g @catppuccin_status_modules_left "session"

# ----------------------------------------------------------
# Right
# ----------------------------------------------------------

set -g @catppuccin_status_modules_right "directory date_time"

# ----------------------------------------------------------
# Session
# ----------------------------------------------------------

set -g @catppuccin_session_icon "󰆍 "
set -g @catppuccin_session_text "#S"

# ----------------------------------------------------------
# Directory
# ----------------------------------------------------------

set -g @catppuccin_directory_icon " "
set -g @catppuccin_directory_text "#{b:pane_current_path}"

# ----------------------------------------------------------
# Date & Time
# ----------------------------------------------------------

set -g @catppuccin_date_time_icon "󰥔 "
set -g @catppuccin_date_time_text "%I:%M %p"
