# ==========================================================
# TMUX
# Main Configuration
#
# This file only loads the modular configuration files.
# ==========================================================

# ----------------------------------------------------------
# Options
# ----------------------------------------------------------
source-file ~/dotfiles/config/tmux/tmux.options.conf

# ----------------------------------------------------------
# Plugins (TPM)
# ----------------------------------------------------------
source-file ~/dotfiles/config/tmux/tmux.plugins.conf

# ----------------------------------------------------------
# Theme (Catppuccin)
# ----------------------------------------------------------
source-file ~/dotfiles/config/tmux/tmux.theme.conf

# ----------------------------------------------------------
# Status Modules
# ----------------------------------------------------------
source-file ~/dotfiles/config/tmux/tmux.modules.conf

# ----------------------------------------------------------
# Keybindings
# ----------------------------------------------------------
source-file ~/dotfiles/config/tmux/tmux.keybinds.conf
